wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 5
gamma:
  value: 0.0006
hidden_layers:
  value:
  - 32
  - 64
  - 128
  - 256
initialization:
  value: Xavier-Normal
learning_rate:
  value: 0.01
optimizer:
  value: adam
weight_decay:
  value: 0
