wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
epochs:
  value: 10
gamma:
  value: 0.002
hidden_layers:
  value:
  - 32
  - 64
  - 128
initialization:
  value: Xavier-Normal
learning_rate:
  value: 0.01
optimizer:
  value: rmsprop
weight_decay:
  value: 0.5
