wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 10
gamma:
  value: 0.0006
hidden_layers:
  value:
  - 32
  - 64
initialization:
  value: Xavier-Normal
learning_rate:
  value: 0.0005
optimizer:
  value: adam
weight_decay:
  value: 0
