wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
epochs:
  value: 5
gamma:
  value: 0.03
hidden_layers:
  value:
  - 32
  - 64
initialization:
  value: Xavier-Normal
learning_rate:
  value: 0.0003
optimizer:
  value: momentum
weight_decay:
  value: 0.0005
