wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 10
gamma:
  value: 0.03
hidden_layers:
  value:
  - 32
  - 64
  - 128
  - 256
initialization:
  value: Xavier-Normal
learning_rate:
  value: 0.0003
optimizer:
  value: rmsprop
weight_decay:
  value: 0.5
