wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 10
gamma:
  value: 0.002
hidden_layers:
  value:
  - 32
  - 64
initialization:
  value: Random
learning_rate:
  value: 0.0006
optimizer:
  value: sgd
weight_decay:
  value: 0.5
