wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
epochs:
  value: 10
gamma:
  value: 0.0006
hidden_layers:
  value:
  - 32
  - 64
  - 128
  - 256
initialization:
  value: Random
learning_rate:
  value: 0.01
optimizer:
  value: nag
weight_decay:
  value: 0
