wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
epochs:
  value: 5
gamma:
  value: 0.002
hidden_layers:
  value:
  - 32
  - 64
  - 128
  - 256
initialization:
  value: Xavier
learning_rate:
  value: 0.0006
optimizer:
  value: nadam
weight_decay:
  value: 0
