wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 10
gamma:
  value: 0.03
hidden_layers:
  value:
  - 32
  - 64
learning_rate:
  value: 0.0006
optimizer:
  value: nadam
weight_decay:
  value: 0
