wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 10
gamma:
  value: 0.0006
hidden_layers:
  value:
  - 32
  - 64
  - 128
  - 256
learning_rate:
  value: 0.0003
optimizer:
  value: sgd
weight_decay:
  value: 0.5
