wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 5
gamma:
  value: 0.001
hidden_layers:
  value:
  - 32
  - 64
learning_rate:
  value: 0.005
optimizer:
  value: sgd
weight_decay:
  value: 0
