wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
epochs:
  value: 10
gamma:
  value: 0.001
hidden_layers:
  value:
  - 32
  - 64
  - 128
learning_rate:
  value: 0.0003
optimizer:
  value: momentum
weight_decay:
  value: 0.0005
