wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 5
gamma:
  value: 0.002
hidden_layers:
  value:
  - 32
  - 64
initialization:
  value: Xavier
learning_rate:
  value: 0.0005
optimizer:
  value: adam
weight_decay:
  value: 0.5
