wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 5
gamma:
  value: 0.002
hidden_layers:
  value:
  - 32
  - 64
  - 128
initialization:
  value: Random
learning_rate:
  value: 0.0003
optimizer:
  value: nadam
weight_decay:
  value: 0
