wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
epochs:
  value: 10
gamma:
  value: 0.03
hidden_layers:
  value:
  - 32
  - 64
  - 128
initialization:
  value: Random
learning_rate:
  value: 0.0001
optimizer:
  value: momentum
weight_decay:
  value: 0.0005
