wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 5
gamma:
  value: 0.03
hidden_layers:
  value:
  - 32
  - 64
  - 128
initialization:
  value: Xavier
learning_rate:
  value: 0.01
optimizer:
  value: nag
weight_decay:
  value: 0
