wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 5
gamma:
  value: 0.0006
hidden_layers:
  value:
  - 32
  - 64
initialization:
  value: Random
learning_rate:
  value: 0.0001
optimizer:
  value: adam
weight_decay:
  value: 0.0005
