wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 10
gamma:
  value: 0.002
hidden_layers:
  value:
  - 32
  - 64
  - 128
initialization:
  value: Random
learning_rate:
  value: 0.0001
optimizer:
  value: rmsprop
weight_decay:
  value: 0
