wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 5
gamma:
  value: 0.0006
hidden_layers:
  value:
  - 32
  - 64
initialization:
  value: Random
learning_rate:
  value: 0.01
optimizer:
  value: rmsprop
weight_decay:
  value: 0.0005
