wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 5
gamma:
  value: 0.0006
hidden_layers:
  value:
  - 32
  - 64
learning_rate:
  value: 0.0005
optimizer:
  value: sgd
weight_decay:
  value: 0.5
