wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1679075023.912524
    t:
      1:
      - 55
      3:
      - 13
      - 23
      4: 3.9.13
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
