wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 5
gamma:
  value: 0.002
hidden_layers:
  value:
  - 32
  - 64
  - 128
  - 256
learning_rate:
  value: 0.0006
optimizer:
  value: adam
weight_decay:
  value: 0.5
