wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 5
gamma:
  value: 0.03
hidden_layers:
  value:
  - 32
  - 64
learning_rate:
  value: 0.0003
optimizer:
  value: rmsprop
weight_decay:
  value: 0.5
