wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
epochs:
  value: 10
gamma:
  value: 0.002
hidden_layers:
  value:
  - 32
  - 64
learning_rate:
  value: 0.005
optimizer:
  value: nag
weight_decay:
  value: 0.5
