wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 5
gamma:
  value: 0.002
hidden_layers:
  value:
  - 32
  - 64
  - 128
  - 256
learning_rate:
  value: 0.0005
optimizer:
  value: momentum
weight_decay:
  value: 0.5
