wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 5
gamma:
  value: 0.0006
hidden_layers:
  value:
  - 32
  - 64
  - 128
learning_rate:
  value: 0.01
optimizer:
  value: sgd
weight_decay:
  value: 0
