wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 10
gamma:
  value: 0.002
hidden_layers:
  value:
  - 32
  - 64
  - 128
  - 256
learning_rate:
  value: 0.005
optimizer:
  value: sgd
weight_decay:
  value: 0
