wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1679083148.594981
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 17
      - 23
      - 37
      4: 3.9.13
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
activation:
  desc: null
  value: tanh
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 5
gamma:
  desc: null
  value: 0.0006
hidden_layers:
  desc: null
  value:
  - 32
  - 64
initialization:
  desc: null
  value: Random
learning_rate:
  desc: null
  value: 0.0005
optimizer:
  desc: null
  value: sgd
weight_decay:
  desc: null
  value: 0.5
