wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1678370169.715682
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      - 37
      4: 3.9.13
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
activation:
  desc: null
  value: tanh
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 5
gamma:
  desc: null
  value: 0.03
hidden_layers:
  desc: null
  value:
  - 32
  - 64
  - 128
learning_rate:
  desc: null
  value: 0.0006
method:
  desc: null
  value: random
metric:
  desc: null
  value:
    goal: maximize
    name: accuracy
optimizer:
  desc: null
  value: rmsprop
parameters:
  desc: null
  value:
    activation:
      values:
      - sigmoid
      - tanh
      - relu
    batch_size:
      values:
      - 16
      - 32
      - 64
    epochs:
      values:
      - 5
      - 10
    gamma:
      values:
      - 0.03
      - 0.0006
      - 0.001
    hidden_layers:
      values:
      - - 32
        - 64
      - - 32
        - 64
        - 128
      - - 32
        - 64
        - 128
        - 256
    learning_rate:
      values:
      - 0.0001
      - 0.005
      - 0.0006
      - 0.01
      - 0.0003
      - 0.0005
    optimizer:
      values:
      - sgd
      - momentum
      - nag
      - rmsprop
      - adam
      - nadam
    weight_decay:
      values:
      - 0.0
      - 0.0005
      - 0.5
weight_decay:
  desc: null
  value: 0
