wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 5
gamma:
  value: 0.001
hidden_layers:
  value:
  - 32
  - 64
  - 128
  - 256
learning_rate:
  value: 0.005
optimizer:
  value: adam
weight_decay:
  value: 0.5
