wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
epochs:
  value: 10
gamma:
  value: 0.002
hidden_layers:
  value:
  - 32
  - 64
  - 128
learning_rate:
  value: 0.005
optimizer:
  value: nadam
weight_decay:
  value: 0
