wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 10
gamma:
  value: 0.03
hidden_layers:
  value:
  - 32
  - 64
initialization:
  value: Xavier
learning_rate:
  value: 0.0001
optimizer:
  value: momentum
weight_decay:
  value: 0.5
