wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1678553879.087779
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 23
      - 37
      4: 3.9.13
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
      10:
      - 5
    viz:
      Confusion matrix:
        historyFieldSettings:
          key: Confusion matrix
          x-axis: _step
        id: wandb/heatmap_no_text/v1
      confusion_matrix:
        historyFieldSettings:
          key: confusion_matrix
          x-axis: _step
        id: wandb/confusion_matrix/v1
activation:
  desc: null
  value: sigmoid
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 10
gamma:
  desc: null
  value: 0.0006
hidden_layers:
  desc: null
  value:
  - 32
  - 64
  - 128
initialization:
  desc: null
  value: Random
learning_rate:
  desc: null
  value: 0.0005
optimizer:
  desc: null
  value: momentum
weight_decay:
  desc: null
  value: 0
